#! /bin/bash

# Script to initialize the creation of the credential store for the test infrastructure.
#
# Bruce Wilson (wilsonbe@ornl.gov)

if [ -z $CRED_STORE_DIR ]; then
	CRED_STORE_DIR=~/.testingstore
fi

if [ -z $CRED_STORE_KEY_LENGTH ]; then
	CRED_STORE_KEY_LENGTH=256
fi

if [ -z $CRED_STORE_KEY_FILE]; then
	CRED_STORE_KEY_FILE=teststore.key
fi


# Check to see if the directory exists

if [ ! -d $CRED_STORE_DIR ] ; then
   mkdir $CRED_STORE_DIR
   chmod 700 $CRED_STORE_DIR
else
   # directory exists, force the permissions
   chmod 700 $CRED_STORE_DIR
fi

# Create a file to be the symmetric encryption key.  
if [ -e $CRED_STORE_DIR/$CRED_STORE_KEY_FILE ]; then
    read -p "Credential key file already exists.  Overwrite? [yY]: " 
    echo 
    if [[ $REPLY =~ ^[Yy][Ee]*[Ss]* ]]; then
    	openssl rand -out $CRED_STORE_DIR/$CRED_STORE_KEY_FILE $CRED_STORE_KEY_LENGTH
    fi
 else
 	openssl rand -out $CRED_STORE_DIR/$CRED_STORE_KEY_FILE $CRED_STORE_KEY_LENGTH
 fi

exit 0
